/// @file message.h
/// Contains the message formats for communication between the controller and pluto.
/// This file should ALWAYS be in sync with `message.py`.
#pragma once

#include <cstdint>
#include <cstddef>

enum class MessageFamilyKind : uint8_t
{
  KIND_INFO,
  KIND_MOVE,
  KIND_SENSOR,
  KIND_BEHAVIOR,
  _count_MessageKind
};

static_assert(
    (uint32_t)MessageFamilyKind::_count_MessageKind <= 4,
    "MessageKind must fit in two bits");

enum class MessageInfoKind : uint8_t
{
  INFO_REQUEST_IS_ALIVE,
  INFO_REQUEST_EVENT_CLOCK,
  INFO_REQUEST_SENSOR,
  INFO_ACKNOWLEDGE, // Payload contains acknowledged sequence_number
};

enum class MessageMoveKind : uint8_t
{
  MOVE_CONTROL_BEGIN_FOR, // Payload duration acts as lease time
  MOVE_CONTROL_END,
  MOVE_STOP_FOR,
  MOVE_BY,
};

enum class MessageSensorKind : uint8_t
{
  SENSOR_DISTANCE,
  SENSOR_MICROPHONE,
};

enum class MessageBehaviorKind : uint8_t
{
  BEHAVIOR_FLIP,
  BEHAVIOR_BOW,
  BEHAVIOR_SIT,
  BEHAVIOR_GIVE_PAW,
};

enum class SensorMicrophone : uint8_t
{
  MIC_NONE,
  MIC_SIT,
  MIC_GIVE_PAW,
  // TODO: add more enum values...
};

#pragma pack(push, 1) // 1-byte alignment for network transmission...
struct Message
{
  /// @brief The MessageFamilyKind
  uint32_t family : 2;
  /// @brief MessageInfoKind | MessageMoveKind | MessageSensorKind
  uint32_t kind : 4;
  /// @brief Event clock (for sensor data), or duration sent by the controller
  uint32_t event_clock_or_duration : 26;

  union
  {
    uint32_t data;

    // INFO
    struct
    {
      MessageSensorKind sensor_kind;
    } info_request_sensor;

    // MOVE
    struct
    {
      int16_t top_bottom_dir;
      int16_t left_right_dir;
    } move_by;

    // SENSORS
    struct
    {
      uint32_t distance; // in mm
    } sensor_distance;

    struct
    {
      SensorMicrophone detected_phrase;
    } sensor_microphone;

    struct
    {
      MessageBehaviorKind behavior_kind;
    } behavior;
  } payload;
};
#pragma pack(pop) // restore default compiler alignment
static_assert(sizeof(Message) == 8, "Message size must be exactly 8 bytes");

/// @brief The maximum number of messages per packet.
/// This was choosen to minimize the overhead of the UDP header,
/// without obtaining immense structs that could make UDP unreliable.
static constexpr uint8_t MAX_MESSAGES_PER_PACKET = 64;

#pragma pack(push, 1) // 1-byte alignment for network transmission...
struct UDPPacket
{
  /// @brief Integrity check for the struct
  uint32_t crc32;
  /// @brief Basic security lock/unlock key (generated by the controller)
  uint32_t session_token;
  /// @brief Used for acknowledges
  uint32_t sequence_number;
  /// @brief Local device time in milliseconds
  uint32_t timestamp;
  /// @brief Number of valid messages in array
  uint8_t message_count;
  /// @brief The messages
  Message messages[MAX_MESSAGES_PER_PACKET];
};
#pragma pack(pop) // restore default compiler alignment

// just to ensure packing for Python struct module...
static_assert(
    sizeof(UDPPacket) == 17 + (8 * MAX_MESSAGES_PER_PACKET),
    "UDPPacket size mismatch");

namespace pluto
{
  inline Message create_move_by(
      int16_t forward_back, int16_t left_right, uint32_t duration_ms)
  {
    Message msg = {}; // zero initialize
    msg.family  = static_cast<uint32_t>(MessageFamilyKind::KIND_MOVE);
    msg.kind    = static_cast<uint32_t>(MessageMoveKind::MOVE_BY);
    msg.event_clock_or_duration        = duration_ms;
    msg.payload.move_by.top_bottom_dir = forward_back;
    msg.payload.move_by.left_right_dir = left_right;
    return msg;
  }

  inline Message create_control_begin(uint32_t lease_duration_ms)
  {
    Message msg = {};
    msg.family  = static_cast<uint32_t>(MessageFamilyKind::KIND_MOVE);
    msg.kind    = static_cast<uint32_t>(MessageMoveKind::MOVE_CONTROL_BEGIN_FOR);
    msg.event_clock_or_duration = lease_duration_ms;
    return msg;
  }

  inline Message create_acknowledge(uint32_t sequence_number)
  {
    Message msg = {};
    msg.family  = static_cast<uint32_t>(MessageFamilyKind::KIND_INFO);
    msg.kind    = static_cast<uint32_t>(MessageInfoKind::INFO_ACKNOWLEDGE);
    msg.event_clock_or_duration = 0;
    msg.payload.data            = sequence_number;
    return msg;
  }

  inline Message create_sensor_distance(
      uint32_t distance_mm, uint32_t current_millis)
  {
    Message msg = {};
    msg.family  = static_cast<uint32_t>(MessageFamilyKind::KIND_SENSOR);
    msg.kind    = static_cast<uint32_t>(MessageSensorKind::SENSOR_DISTANCE);
    msg.event_clock_or_duration          = current_millis;
    msg.payload.sensor_distance.distance = distance_mm;
    return msg;
  }

  inline void init_packet(
      UDPPacket& packet, uint32_t session_token, uint32_t sequence_number,
      uint32_t current_millis)
  {
    packet.session_token   = session_token;
    packet.sequence_number = sequence_number;
    packet.timestamp       = current_millis;
    packet.message_count   = 0;
    packet.crc32           = 0;
  }

  inline bool append_message(UDPPacket& packet, const Message& msg)
  {
    if (packet.message_count >= MAX_MESSAGES_PER_PACKET)
      return false; // buffer full
    packet.messages[packet.message_count] = msg;
    packet.message_count++;
    return true;
  }

  inline uint32_t calculate_crc32(const uint8_t* data, size_t length)
  {
    uint32_t crc = 0xFFFFFFFF;
    for (size_t i = 0; i < length; i++)
    {
      crc ^= data[i];
      for (uint8_t j = 0; j < 8; j++)
      {
        if (crc & 1)
          crc = (crc >> 1) ^ 0xEDB88320;
        else
          crc >>= 1;
      }
    }
    return ~crc;
  }

  inline void finalize_packet_crc(UDPPacket& packet)
  {
    size_t packet_size = 17 + (8 * packet.message_count);

    // skip the first 4 bytes (as this is the checksum...)
    const uint8_t* payload_start = reinterpret_cast<const uint8_t*>(&packet) + 4;
    size_t payload_length        = packet_size - 4;

    packet.crc32 = calculate_crc32(payload_start, payload_length);
  }

  inline bool validate_packet(const UDPPacket& packet, size_t received_bytes)
  {
    if (received_bytes < 17)
      return false;
    size_t expected_size = 17 + (8 * packet.message_count);
    if (received_bytes != expected_size)
      return false;

    // skip the first 4 bytes (as this is the checksum...)
    const uint8_t* payload_start = reinterpret_cast<const uint8_t*>(&packet) + 4;
    size_t payload_length        = expected_size - 4;

    uint32_t computed_crc = calculate_crc32(payload_start, payload_length);
    return computed_crc == packet.crc32;
  }
} // namespace pluto